version: '3.4'

services:
  app:
    build: app/
    restart: on-failure
    tty: true
    stdin_open: true
    network_mode: bridge
    env_file:
      - app/.env
    ports:
      - 5050:5050
    volumes:
      - .:/usr/src/app/
  db:
    build: app/database
    network_mode: bridge
    ports:
      - 54321:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

